# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: SimphiweNkabinde/master-resume-cms

media_folder: /public/media
public_folder: /media

singletons:
  - name: profile
    label: Profile
    file: content/profile.yaml
    fields:
      - { label: First Name, name: firstname }
      - { label: Last Name, name: lastname }
      - { label: Professional Title, name:  professional_title }
      - { label: LinkedIn, name:  linkedin_url, widget: string , type: url }
      - { label: GitHub, name:  github_url, widget: string , type: url  }

collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: /content/posts
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, type: date }
      - { label: Body, name: body, widget: richtext }