# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: SimphiweNkabinde/master-resume-cms

media_folder: /public/media
public_folder: /media

singletons:
  - name: profile
    label: Profile
    icon: account_circle
    file: content/profile.yaml
    fields:
      - { label: First Name, name: firstname }
      - { label: Last Name, name: lastname }
      - { label: Professional Title, name:  professional_title }
      - { label: LinkedIn, name:  linkedin_url, widget: string , type: url }
      - { label: GitHub, name:  github_url, widget: string , type: url  }

collections:
  - name: skills
    label: Skills
    icon: handyman
    folder: /content/skills
    summary: '{{domain}} - {{name}} ({{proficiency}})'
    thumbnail: icon
    fields:
      - {label: Name, name: name, widget: string}
      - {label: Domain, name: domain, widget: select, options: ['programming language', 'frontend', 'backend', 'databases', 'AI', 'UI/UX design', 'collaboration', 'development tools', 'CMS', 'testing', 'messaging', 'monitoring', 'devops']}
      - {label: Proficiency, name: proficiency, widget: select, options: ['strong', 'working', 'familiar']}
      - {label: Icon, name: icon, widget: image, required: false}
  - name: education
    label: Education
    icon: school
    label_singular: education
    folder: /content/education
    summary: '{{qualification}} ({{startdate}} - {{enddate}})'
    thumbnail: '/media/thumbnails/{{slug}}.webp'
    fields:
      - { label: Institution, name: institution, widget: string }
      - { label: Qualification, name: qualification, widget: string }
      - { label: Start date, name: startdate, widget: datetime, type: date }
      - { label: End date, name: enddate, widget: datetime, type: date }
      - { label: Description, name: description, widget: richtext, required: false }
      - { label: Media, name: media, widget: file, required: false}
  