# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: SimphiweNkabinde/master-resume-cms

media_folder: /public/media
public_folder: /media

singletons:
  - name: profile
    label: Profile
    icon: account_circle
    file: content/profile.yaml
    fields:
      - { label: First Name, name: firstname }
      - { label: Last Name, name: lastname }
      - { label: Professional Title, name:  professional_title }
      - { label: LinkedIn, name:  linkedin_url, widget: string , type: url }
      - { label: GitHub, name:  github_url, widget: string , type: url  }

collections:
  - name: skills
    label: Skills
    icon: handyman
    folder: /content/skills
    summary: '{{name}} | {{domain}} ({{proficiency}})'
    thumbnail: icon
    fields:
      - {label: Name, name: name, widget: string}
      - {label: Domain, name: domain, widget: select, options: ['programming language', 'frontend', 'backend', 'databases', 'AI', 'UI/UX design', 'collaboration', 'development tools', 'CMS', 'testing', 'messaging', 'monitoring', 'devops']}
      - {label: Proficiency, name: proficiency, widget: select, options: ['strong', 'working', 'familiar']}
      - {label: Icon, name: icon, widget: image, required: false}
    sortable_fields: [name, domain, proficiency]
  - name: education
    label: Education
    icon: school
    label_singular: education
    folder: /content/education
    summary: "{{qualification}} | {{startdate | date('MMM YYYY')}} - {{enddate | date('MMM YYYY')}}"
    thumbnail: '/media/thumbnails/{{slug}}.webp'
    fields:
      - { label: Institution, name: institution, widget: string }
      - { label: Qualification, name: qualification, widget: string }
      - { label: Start date, name: startdate, widget: datetime, type: date }
      - { label: End date, name: enddate, widget: datetime, type: date }
      - { label: Media, name: media, widget: file, required: false}
  - name: experience
    label: Work Experience
    icon: work
    folder: /content/experience
    summary: "{{job_title}} | {{startdate | date('MMM YYYY')}} - {{enddate | date('MMM YYYY')}}"
    thumbnail: '/media/thumbnails/{{slug}}.webp'
    fields:
      - {label: Job Title, name: job_title}
      - {label: Organization, name: organization}
      - {label: Location, name: location}
      - {label: location Type, name: location_type, widget: select, options: ['on-site', 'hybrid', 'remote']}
      - {label: Employment Type, name: employment_type, widget: select, options: ['full-time', 'part-time', 'contract', 'Internship']}
      - { label: Start date, name: startdate, widget: datetime, type: date }
      - { label: End date, name: enddate, widget: datetime, type: date, required: false }
    sortable_fields: [organization, startdate, job_title]
  - name: certifications
    label: Certifications & Professional Development
    description: Licenses, professional certificates, and courses completed
    icon: workspace_premium
    folder: /content/certifications
    summary: '{{name}}'
    fields:
      - {label: name, name: name}
      - {label: Issuing Organization, name: issuing_organization}
      - {label: Issue Date, name: issue_date, widget: datetime, type: date}
      - {label: Expiration Date, name: expiration_date, widget: datetime, type: date, required: false}
      - {label: Credential ID, name: credential_id, required: false}
      - { label: Credential URL, name:  credential_url, widget: string , type: url, required: false  }
      - { label: Media, name: media, widget: file, required: false}
      
  